### ISSUE TITLE
Is quarkus.ssl.native=true still needed

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#1077]
There are a bunch of examples that has 

quarkus.ssl.native=true

In their application.properties.
And others dont.

Is still still needed? I tried the timer-log example and remove this option and was able to do native compilation and run the example.

**Comment by davsclaus** [comment]
For example timer-log vs timer-log-cdi

**Comment by ppalaga** [comment]
`quarkus.ssl.native=true` is typically not needed in the application.properties, because the underlying extensions requiring SSL produce ExtensionSslNativeSupportBuildItem (same effect) internally.
It is only needed if none of the used extensions produces ExtensionSslNativeSupportBuildItem and the given example is accessing an HTTPS service (or similar) directly.

**Comment by davsclaus** [comment]
Thanks for the detailed feedback. As these timer examples are not using HTTPS, then we can remove them.

**Comment by davsclaus** [comment]
Polished the examples
