### ISSUE TITLE
CassandraQL native support

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#1355]

**Comment by aldettinger** [comment]
Some hurdles in native mode but a quarkus cassandra extension is [on the way](https://github.com/quarkusio/quarkus/issues/7876) and may fix most issues.

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
Fix is blocked by several issues:

- https://datastax-oss.atlassian.net/jira/software/c/projects/JAVA/issues/JAVA-2867
- https://github.com/datastax/cassandra-quarkus/issues/124
- https://github.com/datastax/cassandra-quarkus/issues/123

If mentioned issues are solved, it should be possible to use following changes to add support - https://github.com/JiriOndrusek/camel-quarkus/tree/QUARKUS1355_cassandra-native
(depending on driver version in cassandra-quarkus) it could be necessary to modify runtime/pom to align versions correctly.

**Comment by JiriOndrusek** [comment]
Current status of issues:

- https://datastax-oss.atlassian.net/jira/software/c/projects/JAVA/issues/JAVA-2867 - fixed in driver version 4.9.0. (Camel componet is already updated)
- datastax/cassandra-quarkus#124 - problem could be solved by using parameter `eager-session-init`
- datastax/cassandra-quarkus#123 - next release would contain datastax driver 4.9. 
It should be possible to continue on the solutrion ( by forcing driver version 4.9 even if cassandra-quarkus depends on 4.7.2) 

I'll try to continue with this issue.

**Comment by JiriOndrusek** [comment]
I've asked for an improvement on cassandra-quarkus (https://github.com/datastax/cassandra-quarkus/issues/135), which could make use of `eager-session-init` attribute much more friendly.

**Comment by JiriOndrusek** [comment]
Issue is still blocked. Waiting for release  `1.0.0-alpha4` of `cassandra-quarkus`

**Comment by ppalaga** [comment]
@JiriOndrusek waiting for 1.0.0-alpha4 of cassandra-quarkus may take long. I assume you have some tests in your branch that you could add to the JVM module straight away? That would increase our confidence that the extension works well in the JVM mode at least.

**Comment by jamesnetherton** [comment]
cassandra-quarkus 1.0.0 is out now.

**Comment by JiriOndrusek** [comment]
I'll look into it and try o finish my work

**Comment by JiriOndrusek** [comment]
PR is ready to be merged.

cassandra-quarkus is 1.0.0. Extension needs https://github.com/apache/camel/pull/5051, that is the reason of rebasing to camel-master.
