### ISSUE TITLE
MongoClientName annotation class not available when using camel-quarkus-mongodb extension

### ISSUE THREAD

**Issue by Nillkki** [apache/camel-quarkus#1608]
**Describe the issue**
`@io.quarkus.mongodb.runtime.MongoClientName` -annotation class not available when using `camel-quarkus-mongodb` extension. Annotation works with `quarkus-mongodb-client` but not if both extensions are present.

**To Reproduce**
Add mongo extension and set `quarkus.mongodb.users.connection-string` in application.properties 

Try to inject MongoClient into any bean:
```Java
@Inject
@MongoClientName("users")
MongoClient mongoClient1;
```

Observer `java.lang.NullPointerException: Annotation class not available` -error

**Comment by lburgazzoli** [comment]
@Nillkki do you maybe have a reproducer ?

**Comment by Nillkki** [comment]
> @Nillkki do you maybe have a reproducer ?

Made a repo to reproduce the issue: https://github.com/Nillkki/camel-quarkus-mongo-example

**Comment by lburgazzoli** [comment]
@squakez since you have been working with mongodb, mind having a look ?

**Comment by squakez** [comment]
Yes, I can have a look

**Comment by squakez** [comment]
The issue seems to be related by the fact that we're actually using a default [Mongo Client in camel component extension](https://github.com/apache/camel-quarkus/blob/master/extensions-support/mongodb/deployment/src/main/java/org/apache/camel/quarkus/support/mongodb/deployment/SupportMongoDBProcessor.java#L38). I am trying to debug to see how to fix that and allow the usage of any "named" connection, possibly through `@MongoClientName` annotation.

In the while, my suggestion is to workaround by using that only connection and [configure opportunely](https://camel.apache.org/camel-quarkus/latest/reference/extensions/mongodb.html#_additional_camel_quarkus_configuration).

**Comment by lburgazzoli** [comment]
in any case I think it should not result in a NPE

**Comment by squakez** [comment]
As soon as we fix the issue in the quarkus extension mentioned above we will be able to introduce the concept of a "named" connection in our extension. I am also trying to see if we can use reactive clients in order to be fully compliant with all options available.

**Comment by lburgazzoli** [comment]
@squakez please add references to the issues on quarkus otherwise it is not easy to understand what's going on here.
