### ISSUE TITLE
Hazelcast native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1647]
There is a Hazelcast Client extension by Hazelcast https://github.com/hazelcast/quarkus-hazelcast-client

**Comment by zbendhiba** [comment]
working on this one !!

**Comment by zbendhiba** [comment]
Those 2 issues are blocking the extension to compile on native mode : 
https://issues.apache.org/jira/browse/CAMEL-15820
https://github.com/hazelcast/quarkus-hazelcast-client/issues/94

This issue is blocking the integration tests execution in native mode:
https://github.com/hazelcast/quarkus-hazelcast-client/issues/96
