### ISSUE TITLE
quarkus-spring-web breaks startup of camel-quarkus-activemq

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1759]
placeholder for https://github.com/quarkusio/quarkus/issues/11996

**Comment by jamesnetherton** [comment]
The problem is that `quarkus-spring-di` has this plugin configuration:

```xml
<plugin>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-bootstrap-maven-plugin</artifactId>
    <configuration>
        <excludedArtifacts>
            <excludedArtifact>org.springframework:spring-core</excludedArtifact>
            <excludedArtifact>org.springframework:spring-beans</excludedArtifact>
            <excludedArtifact>org.springframework:spring-context</excludedArtifact>
        </excludedArtifacts>
    </configuration>
</plugin>
```

This effectively bans the core spring libraries from the application. The Quarkus Spring extensions repackage the Spring dependencies and only include a minimal set of packages to reduce the overall footprint. Hence we get a CFNE at runtime.

I don't think there's a simple way to work around this.

We could maybe use a similar approach to Quarkus, where we have our own custom extensions for `spring-jms` / `spring-jdbc` and repackage the Spring bits that we depend on. That would get around the artifact ban.
