### ISSUE TITLE
Wrong jira component version definition in camel-quarkus-bom 1.0.1 file

### ISSUE THREAD

**Issue by zerucus** [apache/camel-quarkus#1775]
In camel-quarkus-bom file version 1.0.1 for jira depenency wrong version is defined
should be` ${camel-quarkus.version}`, but is `${project.version}`:
is:
```
<dependency>
<groupId>org.apache.camel.quarkus</groupId>
<artifactId>camel-quarkus-jira</artifactId>
<version>${project.version}</version>
</dependency>
<dependency>
<groupId>org.apache.camel.quarkus</groupId>
<artifactId>camel-quarkus-jira-deployment</artifactId>
<version>${project.version}</version>
</dependency>
```
should be:
```
<dependency>
<groupId>org.apache.camel.quarkus</groupId>
<artifactId>camel-quarkus-jira</artifactId>
<version>${camel-quarkus.version}</version>
</dependency>
<dependency>
<groupId>org.apache.camel.quarkus</groupId>
<artifactId>camel-quarkus-jira-deployment</artifactId>
<version>${camel-quarkus.version}</version>
</dependency>
```

**Comment by ppalaga** [comment]
Thanks for the report. I have sent a PR fixing this.

This should not be an issue as long as the BOM is imported in dependencyManagement. 

It may cause problems when the BOM is used as a parent. In such causes, the best workaround is to import the BOM in dependencyManagement instead of having it as a parent.

**Comment by zerucus** [comment]
Hello.

 

Thank you for advise.

 

BR,

Zbigniew Krzemińśki
