### ISSUE TITLE
Find a proper place for registering SAXMessages native resource bundle 

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1796]
In https://github.com/apache/camel-quarkus/pull/1793/files#diff-a2ef5a4c98491936f1d708b2ecd89661R83 we register `com.sun.org.apache.xerces.internal.impl.msg.SAXMessages` in our FOP extension. It does not feel like the right place. I guess it should go to our or Quarkus JAXP extension.

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
As a part of Fop extension, there was registered bundle `com.sun.org.apache.xerces.internal.impl.msg.SAXMessages`. Bundle is not necessary for proper functionality but it helps in case there is an exception. 
Example: Real problem is missing reflection registration for some classes, but developer will see only that bundle can not be loaded.
I'd like to add this bundle into camel-quarkus jaxp component, because it can help in future.

> @BuildStep
    NativeImageResourceBundleBuildItem initBundles() {
        return new NativeImageResourceBundleBuildItem(
                "com.sun.org.apache.xerces.internal.impl.msg.SAXMessages");
    }

**Comment by ppalaga** [comment]
See also https://github.com/quarkusio/quarkus/issues/12129

**Comment by ppalaga** [comment]
Solved via https://github.com/quarkusio/quarkus/pull/12144 , esp. https://github.com/quarkusio/quarkus/pull/12144/files#diff-d7d3c24be2a44a5a8077b76e7b3290c6R36 
I have filed https://github.com/apache/camel-quarkus/issues/1806 for the stuff we should do after Quarkus 1.9
