### ISSUE TITLE
Create ASF distribution

### ISSUE THREAD

**Issue by zregvart** [apache/camel-quarkus#2045]
We need a binary distribution to point to as a download from the website. The binary and the source distribution needs to be distributed via Apache mirrors.

**Comment by aldettinger** [comment]
The source distribution is currently managed [manually](https://github.com/apache/camel-quarkus/commit/2b72581fe6ffec2dc8dce49ed2daf0002db53d16).

Still some improvement are possible:
- create releases on reporter.apache.org
  https://reporter.apache.org/addrelease.html?camel
- upload release binaries to dist.apache.org
- group issues for a release, practice varies, especially for
GitHub driven sub-projects, we need to allow users to see what issues
are fixed in what release, maintaining a change log is good, but it's
not parsable and thus of no use on the website (or any other similar
use case)

Documentation references:
- https://www.apache.org/legal/release-policy.html
- https://infra.apache.org/release-publishing.html
- https://infra.apache.org/release-distribution.html

**Comment by ppalaga** [comment]
We group issues using [GH milestones](https://github.com/apache/camel-quarkus/milestones?state=closed) for quite some time.

**Comment by ppalaga** [comment]
Any hints @zregvart what the binary distribution should actually contain for Camel Quarkus?

**Comment by zregvart** [comment]
> Any hints @zregvart what the binary distribution should actually contain for Camel Quarkus?

For Camel (core) we do .zip and .tar.gz containing the built jars, does that make sense for Camel Quarkus?

**Comment by ppalaga** [comment]
> For Camel (core) we do .zip and .tar.gz containing the built jars, does that make sense for Camel Quarkus??

I am struggling to figure out how such a bag of zips could be used for creating a Camel Quarkus application. To be able to use those jars, users need them in some sort of a Maven repo. In other words, zipped Maven repo is perhaps the only kind of binary distribution  that could have some value for the users. But maybe I am overestimating the importance of the usability for the end users. Or maybe somebody sees some other elegant way how to fulfill the ASF rules and at the same time deliver some value to the end users?

**Comment by davsclaus** [comment]
There is no value really for 99% of users. Its for offline / restricted internet users where they need to download a zip with JARs and then put together all the JARs they need themselves. The camel "core" zip is also just only the Camel JARs and has been like that always.

We just need the same for camel-quarkus.

**Comment by zregvart** [comment]
I guess if folk mainly depend on Maven central to pull in binaries, along with dependencies, should we stop distributing binaries as a whole? Perhaps we can take this to the users/dev mailing lists and see what feedback we gather there.

**Comment by ppalaga** [comment]
Yes, creating a Camel Quarkus app is very Maven-repo centric. Whether in Maven or in Gradle based apps, the parts of the application are declared in terms of Maven artifact coordinates and the Quarkus toolling uses given tool's resolution mechanisms to get those parts. 

Note that its impossible to assemble a Camel Quarkus app without Quarkus build Mojo (or the corresponding Gradle task), because that's where the Augmentation (build time analysis and transformation of the application code) is happening.

So there is no way how a user could "put together" an app by moving around jars we give him in a zip file. Unless of course, he installs the jars into his local Maven repo.

Zipped Maven repo is actually a perfect match for the Quarkus process, even in offline environments: it can be unzipped locally and declared as an additional repo in the application's build.gradle, pom.xml or in settings.xml. In that way, the Quarkus tooling can find the necessary artifacts where it expects them.

Having said that I would not mind having a look how we could provide a zipped maven repo containing our binary jars and nothing else.

**Comment by aldettinger** [comment]
The release creation on reporter.apache.org has been added to the [further steps section](https://camel.apache.org/camel-quarkus/latest/contributor-guide/release-guide.html#_further_steps) of the release process.

**Comment by jamesnetherton** [comment]
I think we can close this one now (feel free to reopen if not):

https://issues.apache.org/jira/browse/CAMEL-16038
