### ISSUE TITLE
Consider implementing a vert.x-web based Azure HttpClient

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2196]
We currently rely on the default reactor-netty based Azure [HttpClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpClient.java) , which is not reusing Quarkus event loops.

Cf. the conversation with @cescoffier

> > is it technically possible to wrap vert.x HTTP client into Reactor interfaces - i.e. to make it implement Azure HttpClient? It would perhaps be the most elegant option to support Azure,

> Yes, especially if you use the Mutiny variant of the Vert.x Web Client (Mutiny has adapters for Reactor).

 https://github.com/quarkusio/quarkus/pull/14774#issuecomment-772336353

**Comment by jamesnetherton** [comment]
Whilst it may be desirable to leverage Vert.x, I wonder if it'd be safer to stick with client implementations that are provided by the Azure SDK? Since they're already well proven and running in production systems.

If we want to remove `extensions-support/reactor-netty`, then we could probably do so by switching to the pure JDK client impl:

https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core-http-jdk-httpclient

**Comment by cescoffier** [comment]
Both will lead to wasting a lot of resources. reactor-netty is its own event loop if I'm not mistaken. The JDK HTTP Client is using executors.
