### ISSUE TITLE
camel 3.8 - Removed reflection in 9 components

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#2209]
In Camel 3.8 we have removed reflection in the producer 
https://issues.apache.org/jira/browse/CAMEL-16102

At the following components

camel-atomix
camel-caffeine
camel-consul
camel-corda
camel-ehcache
camel-infinispan
camel-servicenow
camel-spring-redis
camel-web3j

The camel-quarkus extensions of those should be checked if we have any reflection "stuff" we then can remove.

**Comment by davsclaus** [comment]
@jamesnetherton wonder if any of the extensions has some open for reflection which we can remove. We may wait for Lucas PR to merge first to have it work with 3.8 again. 

Mind that some of the components above did not use reflection but was slow by doing annotation scanning on methods, which maybe in graal is possible.

**Comment by jamesnetherton** [comment]
From the list, only caffeine, consul, infinispan & servicenow have native support. None of those extensions have reflective class configuration for any Camel classes, so I think we're in good shape.

I had to add a [reflection hack](https://github.com/apache/camel-quarkus/blob/camel-master/extensions/infinispan/deployment/src/main/java/org/apache/camel/quarkus/component/infinispan/deployment/InfinispanProcessor.java#L34-L41) on the `camel-master` branch for infinispan, but I'll remove before we do the 3.8.0 upgrade since it's no longer needed.

**Comment by jamesnetherton** [comment]
I checked and we are reflection free for those extensions. I cleaned up Netty in https://github.com/apache/camel-quarkus/pull/2232.
