### ISSUE TITLE
plugin update-extension-doc-page fails when running extensions-jvm tests

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#2276]
Reproducer:
* `mvn -U -B -e -fae -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install -f pom.xml -Dquickly -DbuildMetaData.skip -T2.5C` in root folder
* `cd extensions-jvm`
* `mvn -U -B -e -fae -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn verify -f pom.xml -Dformatter.skip -Dimpsort.skip -Denforcer.skip`

Error:
```
Caused by: java.lang.IllegalStateException: Could not find org.apache.camel.quarkus.component.jfr.CamelJfrConfig in /mnt/hudson_workspace/workspace/Integration.next/camel-quarkus/integration-tests/target/asciidoc/generated/config/all-configuration-roots-generated-doc

Failed to execute goal org.apache.camel.quarkus:camel-quarkus-maven-plugin:1.7.0-SNAPSHOT:update-extension-doc-page (update-extension-doc-page) on project camel-quarkus-jfr: Execution update-extension-doc-page of goal org.apache.camel.quarkus:camel-quarkus-maven-plugin:1.7.0-SNAPSHOT:update-extension-doc-page failed: Could not find org.apache.camel.quarkus.component.jfr.CamelJfrConfig in /mnt/hudson_workspace/workspace/Integration.next/camel-quarkus/integration-tests/target/asciidoc/generated/config/all-configuration-roots-generated-doc -> [Help 1]
```

**Comment by ppalaga** [comment]
What is `-DbuildMetaData.skip` supposed to be doing? I do not see any plugin or profile using it.

**Comment by vkasala** [comment]
It's for downstream when QE run the tests from productisation branch.

**Comment by ppalaga** [comment]
Thanks for the report, I was able to reproduce. 

It pops up by JFR, because it is the only JVM-only extension that has a custom Quarkus config. 

The metadata of that config is generated via `io.quarkus.annotation.processor.ExtensionAnnotationProcessor` that in turn is invoked via compiler plugin. As it happens, ExtensionAnnotationProcessor does not produce the metadata when `-Dquickly` is set : https://github.com/quarkusio/quarkus/commit/ce37fb412ec93dda8c56ae66a6af7e2aeacb3c71 so your first maven command does not generate it. Then the second command does not help either because there is no change in the source tree, so the compilation is effectively skipped: 

```
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ camel-quarkus-jfr ---
[INFO] Nothing to compile - all classes are up to date
```

... and thus `update-extension-doc-page` fails because it does not find the metadata file.

As a solution, I suggest to use `-Dcamel-quarkus.update-extension-doc-page.skip` I assume, you do not care for the doc pages. You only want to run the JVM tests

**Comment by ppalaga** [comment]
> I assume, you do not care for the doc pages. 

And even if you did, there is no point in running the mojo, because you are not changing anything that would impact the given extension's doc page.

**Comment by ppalaga** [comment]
Feel free to re-open if `-Dcamel-quarkus.update-extension-doc-page.skip` does not work for you.

**Comment by llowinge** [comment]
@ppalaga It works, thank you for your explanation and tip for resolving the problems.
