### ISSUE TITLE
AWS2 ddb-streams integration tests failures

### ISSUE THREAD

**Issue by mmuzikar** [apache/camel-quarkus#2860]
The integration tests timeout on the ddb-streams part. Rarely 1 stream record of gets through but never the expected 3. 
Interesting fact is that the ddb tests pass just fine, but the streams always fail so the changes are definitely getting created but not observed by camel.

**Comment by jamesnetherton** [comment]
I spent a little bit of time looking at this. I cannot replicate it locally. However, on an underpowered machine it seems to always fail.

One thing I observed was that if you `Thread.sleep()` at the beginning of the test, it will always pass. Which makes me wonder if some how the ddb-streams consumer is getting itself into a state where it never sees any of the events, possibly due to the [`lastSeenSequenceNumber`](https://github.com/apache/camel/blob/main/components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddbstream/Ddb2StreamConsumer.java#L43).

**Comment by ppalaga** [comment]
Sounds like we could do some tricks to make the test pass. Not necessarily Thread.sleep() but some sort of condition that will make the producer requests wait until the consumer has started properly. But I am still wondering whether this is not an issue in the lastSeenSequenceNumber logic?
