### ISSUE TITLE
Use quarkus-maven-plugin:generate-code in GRPC test

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3190]
@jamesnetherton do you see any reason why it would not be possible to use quarkus-maven-plugin:generate-code in our GRPC test? It would simplify the maintenance of io.grpc:protoc-gen-grpc-java:linux-x86_64 and com.google.protobuf:protoc:linux-x86_64 versions

**Comment by jamesnetherton** [comment]
Should be (mostly) ok. AFAIK the Quarkus plugin still does not support all CPU architectures:

https://github.com/quarkusio/quarkus/issues/17886

**Comment by jamesnetherton** [comment]
For this to work, we'd have to add a dependency on `quarkus-grpc`, since that's where the code generator logic lives. Our gRPC extension depends only on `quarkus-grpc-common`.

I guess we could add  `quarkus-grpc` into the itest pom.xml, but I'm not sure if that's the right thing to do. Ideally we want to verify that our stuff works without that dependency being on the classpath.

Or we could request that the codegen stuff is added to `quarkus-grpc-common`, but I'm not sure that makes sense.

**Comment by zhfeng** [comment]
@jamesnetherton I think it only needs to add ```quarkus-grpc-codegen``` in itest since this is used in build time.

**Comment by jamesnetherton** [comment]
> @jamesnetherton I think it only needs to add `quarkus-grpc-codegen` in itest since this is used in build time.

Oh I totally missed that! Thanks @zhfeng. We can probably add it to the deployment part of our gRPC extension.

**Comment by zhfeng** [comment]
yeah, exactly !

**Comment by jamesnetherton** [comment]
In its current form the gRPC codegen is not usable for us. The generated proto stubs are built around the Quarkus gRPC programming model and they reference classes like `io.quarkus.grpc.runtime.MutinyService`.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/5185.
