### ISSUE TITLE
Experiment with the code formatter plugin https://code.revelc.net/formatter-maven-plugin/

### ISSUE THREAD

**Issue by gnodet** [apache/camel-quarkus#337]

**Comment by ppalaga** [comment]
It needs Eclipse formatter settings XML file. What would be your strategy to get one? I started using the one from the main Camel repo and it seems to be quite distant from what we currently have in the camel-quarkus repo.

**Comment by ppalaga** [comment]
impsort-maven-plugin would be also nice for sorting the imports.

https://code.revelc.net/impsort-maven-plugin/

**Comment by lburgazzoli** [comment]
would it be possible to share the same rules with the IDE ? IMH formatting tools to be effective need to be usable straight from the IDE

**Comment by ppalaga** [comment]
The formatter-maven-plugin uses Eclipse JDT under the hood, so it's config file can be directly used in Eclipse. For IntelliJ, IIRC, in the Quarkus ML people mentioned that there is am IJ plugin that supports the Eclipse formatting files.

No idea whether there is some solution for the impsort-maven-plugin. I'd personally would not care, because the imports ordering is quite easy to setup in the IDE manually.
