### ISSUE TITLE
Camel 3.15 - Some dataformats renamed

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#3460]
There are some data formats that have renamed their names, which may affect extensions / unit tests in camel-quarkus that uses those. See the table at
https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_15.adoc#data-formats

**Comment by astefanutti** [comment]
Is the list from https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_15.adoc#data-formats exhaustive, or these are examples?

I'm asking because there are a number of kebab-cased references in the current CamelCatalog resource based on Camel 3.12.0, like `json-jackson`, `protobuf-jackson`, `avro-jackson`, `json-johnzon`, `json-jsonb`, `mime-multipart`, `yaml-snakeyaml`, ... that are not in that list. That being said, I expect the name changes to be picked up automatically once we regenerate the CamelCatalog. But there is some hard-coding for `json-jackson` and the `marshal` DSL to JSON.
