### ISSUE TITLE
Re-enable the FHIR tests once the FHIR testing service is back again

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#352]
Set `quarkus.camel.fhir.enable-dstu3=true` in https://github.com/apache/camel-quarkus/blob/master/integration-tests/fhir/src/main/resources/application.properties#L29

and
```
<quarkus.camel.fhir.enable-dstu2>true</quarkus.camel.fhir.enable-dstu2>
<quarkus.camel.fhir.enable-r4>true</quarkus.camel.fhir.enable-r4>
```
in  https://github.com/apache/camel-quarkus/blob/master/integration-tests/fhir/pom.xml#L81-L82

**Comment by ppalaga** [comment]
@johnpoth I wonder whether it is exceptional that the FHIR testing service is down? 

In case it is rather normal that it is unstable, we should perhaps try to rewrite the test so that it runs only if an initial ping to the service succeeds.

**Comment by lburgazzoli** [comment]
May be better to use something like:

    https://hapifhir.io/doc_server_tester.html

**Comment by johnpoth** [comment]
Hi @ppalaga @lburgazzoli 

As @lburgazzoli pointed out, the goal would be to use our own FHIR server when testing which has been on my TODO list for quite some time (needed in Camel too). 

Ideally we would be using the server here https://github.com/hapifhir/hapi-fhir-jpaserver-starter. It would be cool to automatically find an unused port rather than a hard coded one.

I think we can disable the tests for now, I'll try to work on this sometime next week if that's ok ? Thanks !

**Comment by lburgazzoli** [comment]
@johnpoth had any time to work on this ?

**Comment by johnpoth** [comment]
@lburgazzoli I barely started and got pulled on something else ... should be okay this week :+1:

**Comment by lburgazzoli** [comment]
We do use testcontainers now so we can close this one
