### ISSUE TITLE
`CamelQuarkusQuartzConnectionProvider` should implement `PoolingConnectionProvider`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3750]
I'm not entirely sure how Quartz treats differently `ConnectionProvider` & `PoolingConnectionProvider`. But since Agoral is backing `CamelQuarkusQuartzConnectionProvider`, then it should probably implement `PoolingConnectionProvider` if possible.

**Comment by JiriOndrusek** [comment]
@jamesnetherton There is a problem with `PoolingConnectionProvider`.

In case of `PoolinConectioProvider`Quartz calls different method (with comparison to `ConnectionProvider`) - [code](https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/StdSchedulerFactory.java#L959).  This method propagates all configuration attributes to the **datasource**. Problem is, that before getting the datasource I need to know the DS name, to inject appropriate agroal ds. With `ConnectionProvider` this was not a problem, because datasourceName could be propagated right into the camel-quarkus class - [code](https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/StdSchedulerFactory.java#L961).  

I see several options, how to handle this:

1. Enforce limitation to use only 1 ds -> therefore name is not needed 
2. I can implement a "workaround", which allows configuration of ds name in the same way as with `ConnectionProvider`. There is only 1 limitation - **no other properties** could be set in that way.
3. Better sollution then 1. I can configure through quarkus properties, which one DS should be used for the quartz. Which allow users to define more DSs and select one of them for the quartz. Limitation is, that only 1 DS could be used for the quartz.

My PoV:
Solution 3 is better then 1 -> it limits users to use only 1 DS for quartz cluster (which might cover majority of the use cases)
Solution 2 allows to define several quartz clusters with different DS. (users can not use other properties for connectionPoolProvider as is stated [here](http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html#custom-connectionprovider-implementations))

It should be possible to combination solutions 2 and 3 together (choose 1 DS and configure properties for it or to use more DSs without properties). Do we want to make this configuration too complex?

**Comment by jamesnetherton** [comment]
> Do we want to make this configuration too complex?

It's already quite complex so I guess we should avoid complicating it any further.

Let me think on what to do a bit more. It's probably not super critical that we move to `PoolingConnectionProvider` but it'd be nice if we can find a clean way of doing it.

**Comment by JiriOndrusek** [comment]
Another fact I wasn't considering before. This functionality (clustering via quartz properties) should probably work with the back compatibility - moving any part of the configuration to quarkus's properties is probably not desired. 

I can prepare a "relatively" clean solution, which will allow most of the functionality as is now. We can then discuss over it, whether it is suitable.

**Comment by jamesnetherton** [comment]
Requirement is now superfluous since https://github.com/apache/camel-quarkus/commit/858727e46d6930aefafe302d35d339e7f73e6de6.
