### ISSUE TITLE
Use RestAssured in JDBC test

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#42]
So we use the same style of other tests

**Comment by ppalaga** [comment]
I see at least two reasons why we might not want to do this:

1. Practical: adding resteasy bloats the native image a bit. Compilation will take more time and memory.

2. Methodology: Having resteasy in all itests might cause us miss potential issues in setups without resteasy (because we will never test them). In other words, I think it is good to have itests with non-overlapping dependency sets because in that way, we will cover more mutually independent execution paths.

**Comment by lburgazzoli** [comment]
> I see at least two reasons why we might not want to do this:
> 
>     1. Practical: adding resteasy bloats the native image a bit. Compilation will take more time and memory.
>

It does but I won't sacrifice better testing for some cpu cyle
 
>     2. Methodology: Having resteasy in all itests might cause us miss potential issues in setups without resteasy (because we will never test them). In other words, I think it is good to have itests with non-overlapping dependency sets because in that way, we will cover more mutually independent execution paths.

**No one is saying that we should ban tests that do not use resteasy** but if you look at my PR you can clearly see that the using rest assured + resteasy make the test much easier to write and understand.

**Comment by ppalaga** [comment]
> No one is saying that we should ban tests that do not use resteasy

Nice to hear that. My standpoint is that we should have one or more itests without resteasy. Is this requirement still satisfied after we merge the proposed PR?

**Comment by lburgazzoli** [comment]
You can add one if you wish
