### ISSUE TITLE
perf-regression: introduce version specific build options

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4436]
When trying to compare 2.13.1 with 2.13.2 using

```
java -jar target/quarkus-app/quarkus-run.jar -an 2.13.1 2.13.2
```

I see 2.13.2 failing due to https://github.com/oracle/graal/issues/5303. 

There is a known workaround to use Mandrel image. As far as I can see, there is currently no way to override the builder image for one (preferred) or both of the versions from the command line. I wonder whether it would be possible to introduce such an option.

Actually, for this particular situation, it would be enough to pass `-Dquarkus.native.builder-image=mandrel` both version builds. But being able to set the options for the individual builds separately would be more flexible.

**Comment by aldettinger** [comment]
Trying to summarize, oracle/graal#5303 occurs on some specific environments and has been fixed in native-image 22.3.1. And, we could workaround with an option that would test with mandrel like `--enable-mandrel`.

The tool makes a strong assumption that all camel-quarkus sampled versions are built/tested under similar setup in order to maximize chances to catch meaningful regressions only. So I would advocate to set`mandrel` builder image for all versions under performance regression test.

Moreover, I think this option could be interesting on the long run. Even when testing native-mage <= 22.3.1 would not make sense anymore.

**Comment by aldettinger** [comment]
Ok, I've implemented the option. Let's see how it goes.

**Comment by ppalaga** [comment]
Thanks a lot, @aldettinger !
