### ISSUE TITLE
Add Direct VM extension

### ISSUE THREAD

**Issue by wkrix** [apache/camel-quarkus#4657]
https://github.com/apache/camel/tree/camel-3.20.2/components/camel-directvm

**Comment by jamesnetherton** [comment]
Unfortunately `direct-vm` is marked for deprecation and removal:

https://issues.apache.org/jira/browse/CAMEL-19132

**Comment by wkrix** [comment]
Thanks, somehow I overlooked it.
Could you please tell me what is the alternative to direct vm component?

**Comment by jamesnetherton** [comment]
> Could you please tell me what is the alternative to direct vm component?

The `camel-direct` component would be the replacement.

**Comment by wkrix** [comment]
Does this mean that the communication between different camel contexts will no longer be supported?

**Comment by davsclaus** [comment]
It was never supported. Camel 3.x is a single CamelContext.

**Comment by wkrix** [comment]
Would you mind explaining what you mean by that?
vm and direct-vm components are actively used in our product for this purpose, and we are using Camel 3.18.5 at the moment.

It's from the documentation of direct-vm component:

**Comment by wkrix** [comment]
@davsclaus As I mentioned, our product heavily relies on direct-vm/vm components. Is there a particular reason for deprecating them?

Apart from this, do you have any suggestions on how they might be replaced? The key here is the same JVM - different camel contexts

**Comment by davsclaus** [comment]
You can build your own components

**Comment by davsclaus** [comment]
the migration guide mentions that only 1 `CamelContext` is supported
https://camel.apache.org/manual/camel-3-migration-guide.html#_multiple_camelcontexts_per_application_not_supported

The wording could be more explicit as it refers to _deplyoments_. The old components vm and directvm was only in use in Apache Karaf (multiple deployments) and was forgotten to be removed/deprecated in 3.0.

Camel is a small team and we do not want to support more out of the box than a few runtimes like SB or Quarkus. If you build your own custom platforms or whatever then you must do some stuff on your own.

**Comment by davsclaus** [comment]
and these components are present in 3.x - still possible for you to use or copy as your own components.

**Comment by wkrix** [comment]
For me, the definition of deployment is still blurry. Could you please elaborate what is the meaning of it in case of wildly? Having multiple wars, a single camel context in each is ok?

**Comment by ppalaga** [comment]
> Does this mean that the communication between different camel contexts will no longer be supported?

Camel Quarkus always supported only a single CamelContext per application. Moreover, its life cycle of the CamelContext is controlled by Camel Quarkus rather than by the application developer. The mindset behind Camel Quarkus is mostly motivated by microservices: there is always only one deployment/application per JVM. There is no traditional application server (like WildFly) that would be able to host multiple apps. Quarkus framework takes care for providing some minimal embedded app-server-like environment to expose your app on the network. So if you really need multiple CamelContexts on Camel Quarkus, you probably need multiple applications communicating through the network.
