### ISSUE TITLE
CXF generates different WSDL files with JVM/Native modes

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#4746]
Reproducer https://github.com/llowinge/camel-quarkus-examples/tree/cxf-soap-example/cxf-soap.

With JVM mode it generates correct WSDL at `curl http://0.0.0.0:8081/cxf/services/contact\?wsdl`, but with Native it generates 

```
<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.soap.cxf.acme.org/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/soap/" name="ContactService" targetNamespace="http://service.soap.cxf.acme.org/">
  <wsdl:portType name="ContactServicePortType">
  </wsdl:portType>
  <wsdl:binding name="ContactServiceSoapBinding" type="tns:ContactServicePortType">
    <ns1:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="ContactService">
    <wsdl:port binding="tns:ContactServiceSoapBinding" name="ContactServicePort">
      <ns1:address location="http://0.0.0.0:8081/cxf/services/contact"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
```
When i've added `@WebService` (which should be mandatory - but works in JVM without it) annotation, the WSDL got changed, but still the test didn't pass (but passed in JVM).

**Comment by ppalaga** [comment]
I am not finding any WSDL test in https://github.com/llowinge/camel-quarkus-examples/tree/cxf-soap-example/cxf-soap 
Could you please add it there or even better directly in CQ under `integration-test-groups/cxf-soap/cxf-soap-server`?

Along reviewing and polishing the [java2ws PR](https://github.com/quarkiverse/quarkus-cxf/pull/815) in QCXF I wrote a test that compares the WSDL produced by java2ws with the served one. 
I can confirm that the two WSDLs were not equal unless I added `@WebService(name = "HelloService", serviceName = "HelloService")` to the service interface - that's for JVM mode. I also had to remove the `<soap:address location="">` node because the URL was set to some default `:9090` one in the java2ws document. 
For native mode, I am seeing a correct document being served, but it is indeed slightly different than with JVM mode. The difference is in namespace prefixes. Where JVM has 

`xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"` 

native has 

`xmlns:ns1="http://schemas.xmlsoap.org/wsdl/soap/"` 

Then all occurrences of those prefixes also differ - e.g. 

`<soap:binding .../>`

vs. 

`<ns1:binding .../>`

This should not happen, but I would not say it is a serious bug. The native WSDL correct and mutatis mutandis also equal with the JVM one. 

Is this what you also see in the quickstart?

**Comment by llowinge** [comment]
@ppalaga No, i see much bigger difference (you can easily try it - just run the app in JVM and in Native, then access `curl http://0.0.0.0:8080/cxf/services/contact\?wsdl` and compare it).

I'm attaching the diffchecker (JVM WSDL vs Native WDSL) without `@WebService` - https://www.diffchecker.com/33AqNeTQ/

**Comment by ppalaga** [comment]
The main issue in https://github.com/llowinge/camel-quarkus-examples/tree/cxf-soap-example/cxf-soap was that the Service interface was not annotated with `@WebService`. Without that, quarkus-cxf does not generate necessary helper classes. Adding it revealed two other small issues in quarkus-cxf:

* https://github.com/quarkiverse/quarkus-cxf/issues/821
* https://github.com/quarkiverse/quarkus-cxf/issues/819

Both have fixes now. I am keeping this issue open while the releases 2.0.0 and 1.5.12 of quarkus-cxf reach Camel Quarkus
