### ISSUE TITLE
ical native build failure

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5099]
### Description

Upgrade of ical4j in camel  (see [commit](https://github.com/apache/camel/commit/53a044fa84eda5d08f22ad163b417ecb087cedee)) is causing an error during native execution:

```
UnresolvedElementException: Discovered unresolved method during parsing: net.fortuna.ical4j.validate.schema.JsonSchemaValidator.<init>(java.net.URL). This error is reported at image build time because class net.fortuna.ical4j.validate.schema.SchemaValidatorFactory is registered for linking at image build time by command line
```

It is unclear to me, why the error is happening, because the Quarkus knows this class.

I noticed, that this method is not visited  during Camel or Camel Quarkus tests execution. Therefore it might be possible, that the method is not needed for the Camel/camel quarkus, I fixed the problem temporarily by the workaround (substitution of the method). It would be nice to investigate the problem more and if it is possible to trigger this validation from Camel/Camel Quarkus -> the case should be covered by the tests.

**Comment by jamesnetherton** [comment]
It likely happens because `com.github.erosb:everit-json-schema` is declared as `runtime` scope and `optional`.

We could make the method substitution conditional based on the presence of some class in `everit-json-schema`.

Example of how I did something similar for another extension here https://github.com/apache/camel-quarkus/pull/4926.
