### ISSUE TITLE
camel application property routesUri is not overridden at runtime

### ISSUE THREAD

**Issue by alainpham** [apache/camel-quarkus#54]
**Describe the bug**
When using the camel extension, the application property `quarkus.camel.routes-uris` is not overridden at run time with the native executable. It should be in `ConfigPhase.RUN_TIME` instead of `ConfigPhase.BUILD_AND_RUN_TIME_FIXED`.
[Original discussion here](https://github.com/quarkusio/quarkus/issues/3116)

**Expected behavior**
When overriding application property `routes-uris` with a config/application.properties file or environment variable, it should be taken into at run time by the executable.

**Actual behavior**
Still takes the value from the development version in resources/application.properties no matter what.

**To Reproduce**
1. ```git clone https://github.com/alainpham/quarkus-kafka-camel-servlet.git```
2. ```cd quarkus-kafka-camel-servlet```
3. Add some configuration change regarding camel in the docker-compose.xml as environment vars file. We can try to change the url patterns or the uris to the routes.xml.
```
    environment:
      - 'QUARKUS_CAMEL_ROUTES_URIS=file:/camel/routessss.xml'
```
4. ```docker-compose up```
5. The new values are not taken into account

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 3.10.0-957.21.3.el7.x86_64
 - Output of `java -version`: 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
 - GraalVM version (if different from Java): 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183340.buildslave.jdk8u-src-tar--b03)
OpenJDK 64-Bit GraalVM CE 19.0.2 (build 25.212-b03-jvmci-19-b04, mixed mode)
```
 - Quarkus version or git rev: 0.18.0

**Comment by ppalaga** [comment]
Moving `routesUris` from `BUILD_AND_RUN_TIME_FIXED` to `RUN_TIME` would make it impossible to do the build time materialization of the routes (because the RUNTIME config is simply not available at runtime). I do not think we want to do that. WDYT, @lburgazzoli?

As an alternative, we could perhaps add runtime `routesUris` config option to the existing build time one. The new runtime option would have the semantics requested by @alainpham.

As a workaround, we can recommend the technique used in the [core-cdi itest](https://github.com/apache/camel-quarkus/blob/master/integration-tests/core-cdi/src/main/java/org/apache/camel/quarkus/component/core/cdi/CamelApplication.java#L43). We use a path literal there, but you could make it dynamic by using a field annotated with something like `@ConfigProperty(name = "your.runtime.path")`

**Comment by ppalaga** [comment]
Agreed with @gnodet  and others to move the property to RUN_TIME.

**Comment by Silvakilla** [comment]
Has this ever been implemented so far?

**Comment by lburgazzoli** [comment]
will work on it now
