### ISSUE TITLE
Camel 4.9 - Add boot clock to CamelContext to capture boot time

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#6630]
### Describe the feature here

There is some processing happening before camel context is started and that boot time is now captured in CSB with
https://github.com/apache/camel-spring-boot/commit/32530b8c08237d9f3d024ec69596f3e47c64a1a6

So maybe in CEQ where xxxCamelContext is created the first time, then the boot clock can be added.
That allows Camel to show the boot time spent during its startup message.

**Comment by jamesnetherton** [comment]
This can work ok for JVM mode. 

In native mode, the 'boot' is done during `STATIC_INIT`. So the initial timestamp of when the clock is created will be baked into the native image, which leads to an inaccurate calculation when the boot time is printed.

We should probably just return `null` for the BOOT clock in native mode, since that phase is done at build time.

**Comment by davsclaus** [comment]
yeah you can return null in native mode
