### ISSUE TITLE
quarkus-camel - Migrate option prefixes

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#8]
When using camel-quarkus we should migrate the option prefix from

- quarkus.camel.disable-xml=true
- quarkus.camel.disable-jaxb=true

To be using

- camel.quarkus.xxx=yyy

**Comment by ppalaga** [comment]
What is the motivation for this change? Asking because the property naming conventions are currently discussed on quarkus-dev ML [1] and we should perhaps enrich the discussion with our perspective.

[1] https://groups.google.com/forum/#!topic/quarkus-dev/eyLaDlACNoE

**Comment by lburgazzoli** [comment]
I think that for extension related properties - so those that influence the build phase - we should keep the `quarkus.camel` prefix, for camel runtime related properties instead we should keep our conventions as those are mainly runtime properties (host, ports) and because they are then consistent across platforms (i.e. spring boot) and tooling.

**Comment by davsclaus** [comment]
Yeah what Luca says is good, that some options that are quarkus build time only can be with quarkus, but all the other Camel options should be aligned across - camel k, canel quarkus, camel main, camel spring boot etc.

**Comment by ppalaga** [comment]
Posted our standpoint on quarkus-dev: https://groups.google.com/d/msg/quarkus-dev/eyLaDlACNoE/mi7AQsC7CgAJ
