### ISSUE TITLE
Duplicate LICENSE(.txt) and NOTICE(.txt) files in the source distribution

### ISSUE THREAD

**Issue by gnodet** [apache/camel-quarkus#844]

**Comment by ppalaga** [comment]
@gnodet could you please sketch how did you find this issue? I have an idea where the problem is but I'd like to make sure that my fix will meet your acceptance criteria.

**Comment by ppalaga** [comment]
I mean, how do I build the source distro?

**Comment by gnodet** [comment]
I don't know, i just unzipped the source distribution that was being voted.
I don't see any maven assembly plugin though, it may be inherited from the apache parent pom. @oscerd any idea as you did the release ?

**Comment by oscerd** [comment]
It should come from the apache parent pom and pass through the release profile

**Comment by ppalaga** [comment]
OK, let me try `mvn -Prelease release:prepare -DpushChanges=false`

**Comment by ppalaga** [comment]
I was able to reproduce using `mvn -Papache-release release:prepare -DpushChanges=false`. 

I'd say the extension-less `NOTICE` and `LICENSE` files are unwanted. They come via `org.apache.apache.resources:apache-source-release-assembly-descriptor` artifact that is added as a dependency of the assembly plugin in the apache parent: https://github.com/apache/maven-apache-parent/blob/apache-21/pom.xml#L352-L378

It does not happen with Camel because Camel seems to provide its own assembly descriptor in https://github.com/apache/camel/blob/master/apache-camel/pom.xml#L227 . We should perhaps do the same. WDYT?
