### ISSUE TITLE
Camel-Catalog-Quarkus: It is missing for release-1.0.0-M5

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#904]
Actually the camel-catalog-quarkus for the last release is missing

https://search.maven.org/artifact/org.apache.camel.quarkus/camel-catalog-quarkus

I believe this is related to https://github.com/apache/camel-quarkus/pull/869

**Comment by oscerd** [comment]
Just discovered it has been renamed to camel-quarkus-catalog. Is there a specific reason for this?

**Comment by oscerd** [comment]
By the way, mistery resolved.

**Comment by oscerd** [comment]
Let me re-open, maybe it makes sense to switch back to the original name.

**Comment by lburgazzoli** [comment]
We probably should follow the naming used in other projects so as we have 

- camel-catalog-provider-karaf
- camel-catalog-provider-springboot

Maybe we should name this `camel-catalog-provider-quarkus`

@davsclaus @oscerd  what do you think ?

**Comment by oscerd** [comment]
Sounds good to me. I'll open a PR if it's ok for all.

**Comment by ppalaga** [comment]
Agreed with @oscerd that I'll fix this.

**Comment by ppalaga** [comment]
> Is there a specific reason for this?

I wanted to follow the convention that all artifactIds start with `camel-quarkus-`. Having the same prefix for all modules in a source tree is quite common in the maven world. It is practical because e.g. naming clashes are less likely when jars need to be copied into a single directory (libs dir in quarkus or some sort of deployments directory on a web-container). Also Eclipse needs manual workarounds to import two modules from two separate source trees having the same artifactId.

The old artifactId was used both in Camel and Camel Quarkus, IIRC.

The proposed camel-catalog-provider-quarkus follows another naming convention but it is at least globally unique (which makes it acceptable). But I still wonder why that naming convention should be held superior to the local naming convention? Are all the catalog providers pulled by some agent who makes assumptions about their names?

**Comment by ppalaga** [comment]
@lburgazzoli  is there any reason why the naming convention proposed by you should be held superior to the local naming convention? Are all the catalog providers pulled by some agent who makes assumptions about their names?

**Comment by lburgazzoli** [comment]
Its just a matter of using the same naming convention across sub-projects, if you think there's a better naming scheme maybe open a discussion on the dev mainiling list.
